import type { WineClubState } from "@/types/wine";

export function createSeedData(): WineClubState {
  return {
    version: 1,
    batches: [
      {
        id: "batch-blackberry-cabernet",
        name: "Midnight Jam",
        varietal: "Blackberry Cabernet",
        style: "Fruit",
        volumeGallons: 6,
        currentPhase: "Racked",
        phaseHistory: [
          { phase: "Started", date: "2026-06-06" },
          { phase: "Racked", date: "2026-07-05" },
        ],
        notes: "Deep berry aroma. Let the tannins soften before the next tasting.",
        createdAt: "2026-06-06",
      },
      {
        id: "batch-peach-chardonnay",
        name: "Porch Swing",
        varietal: "Peach Chardonnay",
        style: "White",
        volumeGallons: 5,
        currentPhase: "Started",
        phaseHistory: [{ phase: "Started", date: "2026-07-08" }],
        notes: "Fermenting cool for a bright, fresh finish.",
        createdAt: "2026-07-08",
      },
      {
        id: "batch-elderberry-merlot",
        name: "Velvet Rope",
        varietal: "Elderberry Merlot",
        style: "Red",
        volumeGallons: 6,
        currentPhase: "Bottled",
        phaseHistory: [
          { phase: "Started", date: "2026-02-14" },
          { phase: "Racked", date: "2026-03-21" },
          { phase: "Bottled", date: "2026-05-22" },
        ],
        notes: "Thirty bottles resting. First bottle opens in September.",
        createdAt: "2026-02-14",
      },
    ],
    readings: [
      {
        id: "reading-1",
        batchId: "batch-blackberry-cabernet",
        date: "2026-07-12",
        stage: "After first rack",
        specificGravity: 0.998,
        temperatureF: 68,
        ph: 3.42,
        notes: "Dry and clearing nicely.",
      },
      {
        id: "reading-2",
        batchId: "batch-peach-chardonnay",
        date: "2026-07-11",
        stage: "Primary fermentation",
        specificGravity: 1.062,
        temperatureF: 64,
        ph: 3.31,
        notes: "Steady airlock activity.",
      },
      {
        id: "reading-3",
        batchId: "batch-elderberry-merlot",
        date: "2026-05-21",
        stage: "Pre-bottling",
        specificGravity: 0.996,
        temperatureF: 67,
        ph: 3.48,
        notes: "Stable for three consecutive readings.",
      },
    ],
    additions: [
      {
        id: "addition-1",
        batchId: "batch-blackberry-cabernet",
        date: "2026-07-05",
        agent: "Potassium metabisulfite",
        amount: 0.25,
        unit: "tsp",
        notes: "Added at first racking.",
      },
      {
        id: "addition-2",
        batchId: "batch-peach-chardonnay",
        date: "2026-07-08",
        agent: "Pectic enzyme",
        amount: 2.5,
        unit: "tsp",
        notes: "Mixed into must before pitching yeast.",
      },
      {
        id: "addition-3",
        batchId: "batch-peach-chardonnay",
        date: "2026-07-09",
        agent: "Lalvin 71B yeast",
        amount: 1,
        unit: "packet",
        notes: "Rehydrated at 95°F.",
      },
    ],
    meetings: [
      {
        id: "meeting-1",
        date: "2026-07-19",
        title: "July cellar night",
        attendees: ["Maya", "Jordan", "Alex", "Sam", "Casey"],
        notes: "Taste Midnight Jam, check Porch Swing SG, and sanitize the bottle tree.",
      },
      {
        id: "meeting-2",
        date: "2026-07-05",
        title: "Rack & relax",
        attendees: ["Maya", "Jordan", "Sam", "Casey"],
        notes: "Racked Midnight Jam. Agreed to age Velvet Rope until September.",
      },
      {
        id: "meeting-3",
        date: "2026-06-06",
        title: "Summer crush kickoff",
        attendees: ["Maya", "Jordan", "Alex", "Sam"],
        notes: "Started Midnight Jam and assigned weekly reading check-ins.",
      },
    ],
  };
}
